[project]
name = "pysc2-converter-external"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kaszanas", email = "34846245+Kaszanas@users.noreply.github.com" }
]
requires-python = ">=3.10"
dependencies = [
    "grpcio>=1.78.0",
    "protobuf<3.21.0",
    "pysc2>=4.0.0",
    "s2clientprotocol>=5.0.15.95299.0",
    "s2protocol>=5.0.15.95299.0",
]


[dependency-groups]
dev = [
    "commitizen>=4.13.9",
    "pytest>=9.0.2",
    "ruff>=0.15.6",
]

[tool.uv.sources]
s2protocol = { git = "https://github.com/Kaszanas/s2protocol" }



[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

