"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import s2clientprotocol.common_pb2
import s2clientprotocol.sc2api_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ConverterSettings(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class RawSettings(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class CameraDimensions(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            LEFT_FIELD_NUMBER: builtins.int
            RIGHT_FIELD_NUMBER: builtins.int
            TOP_FIELD_NUMBER: builtins.int
            BOTTOM_FIELD_NUMBER: builtins.int
            left: builtins.float
            right: builtins.float
            top: builtins.float
            bottom: builtins.float
            def __init__(
                self,
                *,
                left: builtins.float | None = ...,
                right: builtins.float | None = ...,
                top: builtins.float | None = ...,
                bottom: builtins.float | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing_extensions.Literal["bottom", b"bottom", "left", b"left", "right", b"right", "top", b"top"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing_extensions.Literal["bottom", b"bottom", "left", b"left", "right", b"right", "top", b"top"]) -> None: ...

        RESOLUTION_FIELD_NUMBER: builtins.int
        MAX_UNIT_COUNT_FIELD_NUMBER: builtins.int
        NUM_UNIT_FEATURES_FIELD_NUMBER: builtins.int
        MAX_UNIT_SELECTION_SIZE_FIELD_NUMBER: builtins.int
        SHUFFLE_UNIT_TAGS_FIELD_NUMBER: builtins.int
        ENABLE_ACTION_REPEAT_FIELD_NUMBER: builtins.int
        USE_CAMERA_POSITION_FIELD_NUMBER: builtins.int
        CAMERA_FIELD_NUMBER: builtins.int
        USE_VIRTUAL_CAMERA_FIELD_NUMBER: builtins.int
        VIRTUAL_CAMERA_DIMENSIONS_FIELD_NUMBER: builtins.int
        ADD_EFFECTS_TO_UNITS_FIELD_NUMBER: builtins.int
        ADD_CARGO_TO_UNITS_FIELD_NUMBER: builtins.int
        MASK_OFFSCREEN_ENEMIES_FIELD_NUMBER: builtins.int
        @property
        def resolution(self) -> s2clientprotocol.common_pb2.Size2DI:
            """The resolution of the raw coordinate grid."""
        max_unit_count: builtins.int
        """The maximum number of units which can be observed."""
        num_unit_features: builtins.int
        """The number of features to output for each raw unit."""
        max_unit_selection_size: builtins.int
        """The maximum number of units which can be selected, and so issued with
        an action in a single command.
        """
        shuffle_unit_tags: builtins.int
        """Whether to shuffle raw_units observations."""
        enable_action_repeat: builtins.bool
        """Whether to enable action repeat; the ability to send multiple actions on
        the same frame.
        """
        use_camera_position: builtins.bool
        """Adds "camera_position" and "camera_size" to the observation."""
        camera: builtins.bool
        """Adds "camera" to the observation."""
        use_virtual_camera: builtins.bool
        """Whether to replace all camera-based features based on a virtual camera."""
        @property
        def virtual_camera_dimensions(self) -> global___ConverterSettings.RawSettings.CameraDimensions: ...
        add_effects_to_units: builtins.bool
        """Effects can be passed to the agents by including them in the list of
        units.
        """
        add_cargo_to_units: builtins.bool
        """Cargo can be passed to the agents by including them in the list of units."""
        mask_offscreen_enemies: builtins.bool
        """The native raw interface doesn't care for the camera. This option
        masks out apt data for enemies which are offscreen, meaning the agent
        needs to be looking at them to collect full data - as a human does.
        """
        def __init__(
            self,
            *,
            resolution: s2clientprotocol.common_pb2.Size2DI | None = ...,
            max_unit_count: builtins.int | None = ...,
            num_unit_features: builtins.int | None = ...,
            max_unit_selection_size: builtins.int | None = ...,
            shuffle_unit_tags: builtins.int | None = ...,
            enable_action_repeat: builtins.bool | None = ...,
            use_camera_position: builtins.bool | None = ...,
            camera: builtins.bool | None = ...,
            use_virtual_camera: builtins.bool | None = ...,
            virtual_camera_dimensions: global___ConverterSettings.RawSettings.CameraDimensions | None = ...,
            add_effects_to_units: builtins.bool | None = ...,
            add_cargo_to_units: builtins.bool | None = ...,
            mask_offscreen_enemies: builtins.bool | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["add_cargo_to_units", b"add_cargo_to_units", "add_effects_to_units", b"add_effects_to_units", "camera", b"camera", "enable_action_repeat", b"enable_action_repeat", "mask_offscreen_enemies", b"mask_offscreen_enemies", "max_unit_count", b"max_unit_count", "max_unit_selection_size", b"max_unit_selection_size", "num_unit_features", b"num_unit_features", "resolution", b"resolution", "shuffle_unit_tags", b"shuffle_unit_tags", "use_camera_position", b"use_camera_position", "use_virtual_camera", b"use_virtual_camera", "virtual_camera_dimensions", b"virtual_camera_dimensions"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["add_cargo_to_units", b"add_cargo_to_units", "add_effects_to_units", b"add_effects_to_units", "camera", b"camera", "enable_action_repeat", b"enable_action_repeat", "mask_offscreen_enemies", b"mask_offscreen_enemies", "max_unit_count", b"max_unit_count", "max_unit_selection_size", b"max_unit_selection_size", "num_unit_features", b"num_unit_features", "resolution", b"resolution", "shuffle_unit_tags", b"shuffle_unit_tags", "use_camera_position", b"use_camera_position", "use_virtual_camera", b"use_virtual_camera", "virtual_camera_dimensions", b"virtual_camera_dimensions"]) -> None: ...

    class VisualSettings(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SCREEN_FIELD_NUMBER: builtins.int
        SCREEN_FEATURES_FIELD_NUMBER: builtins.int
        @property
        def screen(self) -> s2clientprotocol.common_pb2.Size2DI:
            """The resolution of the screen feature planes."""
        @property
        def screen_features(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
            """The screen feature planes to include in the observation."""
        def __init__(
            self,
            *,
            screen: s2clientprotocol.common_pb2.Size2DI | None = ...,
            screen_features: collections.abc.Iterable[builtins.str] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["screen", b"screen"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["screen", b"screen", "screen_features", b"screen_features"]) -> None: ...

    RAW_SETTINGS_FIELD_NUMBER: builtins.int
    VISUAL_SETTINGS_FIELD_NUMBER: builtins.int
    MINIMAP_FIELD_NUMBER: builtins.int
    MINIMAP_FEATURES_FIELD_NUMBER: builtins.int
    NUM_ACTION_TYPES_FIELD_NUMBER: builtins.int
    NUM_UNIT_TYPES_FIELD_NUMBER: builtins.int
    NUM_UPGRADE_TYPES_FIELD_NUMBER: builtins.int
    MAX_NUM_UPGRADES_FIELD_NUMBER: builtins.int
    CAMERA_WIDTH_WORLD_UNITS_FIELD_NUMBER: builtins.int
    MMR_FIELD_NUMBER: builtins.int
    SUPERVISED_FIELD_NUMBER: builtins.int
    CROP_TO_PLAYABLE_AREA_FIELD_NUMBER: builtins.int
    ADD_OPPONENT_FEATURES_FIELD_NUMBER: builtins.int
    @property
    def raw_settings(self) -> global___ConverterSettings.RawSettings: ...
    @property
    def visual_settings(self) -> global___ConverterSettings.VisualSettings: ...
    @property
    def minimap(self) -> s2clientprotocol.common_pb2.Size2DI:
        """The resolution of the minimap feature planes."""
    @property
    def minimap_features(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """The minimap feature planes to include in the observation."""
    num_action_types: builtins.int
    """This is the number of action types that are available. It is specified
    as part of the converter to provide a consistent view of the game even
    when versions change and the number of action types increases.
    """
    num_unit_types: builtins.int
    """This is the number of unit types that are available. It is specified
    as part of the converter to provide a consistent view of the game even
    when versions change and the number of unit types increases.
    """
    num_upgrade_types: builtins.int
    """This is the number of upgrade types that are available. It is specified
    as part of the converter to provide a consistent view of the game even
    when versions change and the number of upgrade types increases.
    """
    max_num_upgrades: builtins.int
    """This is the maximum number of upgrades that can be observed in a frame.
    It is the length of the upgrades_fixed_length observation.
    """
    camera_width_world_units: builtins.int
    """The width of the camera view."""
    mmr: builtins.int
    """When not in a replay, this MMR will be reflected in the observation.
    When in a replay this value is ignored and the MMR of the replay used.
    """
    supervised: builtins.bool
    """Flag to indicate whether the converter is being used for supervised
    training. If so, the action chosen on each observation must be passed
    in to the converter, and that action will be reflected in the observation.
    """
    crop_to_playable_area: builtins.bool
    """Whether to crop the minimal (if visual) or map and resolution (if raw)
    down to the playable area such that detail is maximized.
    """
    add_opponent_features: builtins.bool
    """Flag which determines whether opponent features are added to the
    observation. The names of these features all begin `opponent_`. They can
    only be made available when the `opponent` observation is passed as part
    of the transformed Observation. Note that these observations are only
    intended for training; they provide privileged information about the
    opponent and so their use in evaluation would be cheating. Obviously this
    isn't an issue when connecting to a remote game, such as playing vs a
    human over LAN or Battle.net, but care should be taken when evaluating
    in a situation when both players are being processed locally.
    """
    def __init__(
        self,
        *,
        raw_settings: global___ConverterSettings.RawSettings | None = ...,
        visual_settings: global___ConverterSettings.VisualSettings | None = ...,
        minimap: s2clientprotocol.common_pb2.Size2DI | None = ...,
        minimap_features: collections.abc.Iterable[builtins.str] | None = ...,
        num_action_types: builtins.int | None = ...,
        num_unit_types: builtins.int | None = ...,
        num_upgrade_types: builtins.int | None = ...,
        max_num_upgrades: builtins.int | None = ...,
        camera_width_world_units: builtins.int | None = ...,
        mmr: builtins.int | None = ...,
        supervised: builtins.bool | None = ...,
        crop_to_playable_area: builtins.bool | None = ...,
        add_opponent_features: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["add_opponent_features", b"add_opponent_features", "camera_width_world_units", b"camera_width_world_units", "crop_to_playable_area", b"crop_to_playable_area", "interface_settings", b"interface_settings", "max_num_upgrades", b"max_num_upgrades", "minimap", b"minimap", "mmr", b"mmr", "num_action_types", b"num_action_types", "num_unit_types", b"num_unit_types", "num_upgrade_types", b"num_upgrade_types", "raw_settings", b"raw_settings", "supervised", b"supervised", "visual_settings", b"visual_settings"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["add_opponent_features", b"add_opponent_features", "camera_width_world_units", b"camera_width_world_units", "crop_to_playable_area", b"crop_to_playable_area", "interface_settings", b"interface_settings", "max_num_upgrades", b"max_num_upgrades", "minimap", b"minimap", "minimap_features", b"minimap_features", "mmr", b"mmr", "num_action_types", b"num_action_types", "num_unit_types", b"num_unit_types", "num_upgrade_types", b"num_upgrade_types", "raw_settings", b"raw_settings", "supervised", b"supervised", "visual_settings", b"visual_settings"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["interface_settings", b"interface_settings"]) -> typing_extensions.Literal["raw_settings", "visual_settings"] | None: ...

global___ConverterSettings = ConverterSettings

class EnvironmentInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GAME_INFO_FIELD_NUMBER: builtins.int
    REPLAY_INFO_FIELD_NUMBER: builtins.int
    @property
    def game_info(self) -> s2clientprotocol.sc2api_pb2.ResponseGameInfo: ...
    @property
    def replay_info(self) -> s2clientprotocol.sc2api_pb2.ResponseReplayInfo: ...
    def __init__(
        self,
        *,
        game_info: s2clientprotocol.sc2api_pb2.ResponseGameInfo | None = ...,
        replay_info: s2clientprotocol.sc2api_pb2.ResponseReplayInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["game_info", b"game_info", "replay_info", b"replay_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["game_info", b"game_info", "replay_info", b"replay_info"]) -> None: ...

global___EnvironmentInfo = EnvironmentInfo

class Observation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLAYER_FIELD_NUMBER: builtins.int
    OPPONENT_FIELD_NUMBER: builtins.int
    FORCE_ACTION_FIELD_NUMBER: builtins.int
    FORCE_ACTION_DELAY_FIELD_NUMBER: builtins.int
    @property
    def player(self) -> s2clientprotocol.sc2api_pb2.ResponseObservation: ...
    @property
    def opponent(self) -> s2clientprotocol.sc2api_pb2.ResponseObservation:
        """Used for opponent's observation during training."""
    @property
    def force_action(self) -> s2clientprotocol.sc2api_pb2.RequestAction:
        """Used for supervised learning."""
    force_action_delay: builtins.int
    def __init__(
        self,
        *,
        player: s2clientprotocol.sc2api_pb2.ResponseObservation | None = ...,
        opponent: s2clientprotocol.sc2api_pb2.ResponseObservation | None = ...,
        force_action: s2clientprotocol.sc2api_pb2.RequestAction | None = ...,
        force_action_delay: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["force_action", b"force_action", "force_action_delay", b"force_action_delay", "opponent", b"opponent", "player", b"player"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["force_action", b"force_action", "force_action_delay", b"force_action_delay", "opponent", b"opponent", "player", b"player"]) -> None: ...

global___Observation = Observation

class Action(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REQUEST_ACTION_FIELD_NUMBER: builtins.int
    DELAY_FIELD_NUMBER: builtins.int
    @property
    def request_action(self) -> s2clientprotocol.sc2api_pb2.RequestAction: ...
    delay: builtins.int
    """Game loops after which we would like our next observation."""
    def __init__(
        self,
        *,
        request_action: s2clientprotocol.sc2api_pb2.RequestAction | None = ...,
        delay: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["delay", b"delay", "request_action", b"request_action"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["delay", b"delay", "request_action", b"request_action"]) -> None: ...

global___Action = Action

class RecordedEpisode(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GAME_INFO_FIELD_NUMBER: builtins.int
    OBSERVATIONS_FIELD_NUMBER: builtins.int
    @property
    def game_info(self) -> s2clientprotocol.sc2api_pb2.ResponseGameInfo: ...
    @property
    def observations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Observation]: ...
    def __init__(
        self,
        *,
        game_info: s2clientprotocol.sc2api_pb2.ResponseGameInfo | None = ...,
        observations: collections.abc.Iterable[global___Observation] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["game_info", b"game_info"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["game_info", b"game_info", "observations", b"observations"]) -> None: ...

global___RecordedEpisode = RecordedEpisode
