"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Import from pysc2 protos the definitions for the message that is required:"""
import builtins
import collections.abc
import pysc2_converter_external.proto.converter_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class ConfigureRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SETTINGS_FIELD_NUMBER: builtins.int
    ENVIRONMENT_INFO_FIELD_NUMBER: builtins.int
    @property
    def settings(self) -> converter_pb2.ConverterSettings: ...
    @property
    def environment_info(self) -> converter_pb2.EnvironmentInfo: ...
    def __init__(
        self,
        *,
        settings: converter_pb2.ConverterSettings | None = ...,
        environment_info: converter_pb2.EnvironmentInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["environment_info", b"environment_info", "settings", b"settings"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["environment_info", b"environment_info", "settings", b"settings"]) -> None: ...

global___ConfigureRequest = ConfigureRequest

class ConfigureResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    SESSION_ID_FIELD_NUMBER: builtins.int
    success: builtins.bool
    """Whether the converter was successfully configured."""
    session_id: builtins.int
    def __init__(
        self,
        *,
        success: builtins.bool | None = ...,
        session_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["session_id", b"session_id", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["session_id", b"session_id", "success", b"success"]) -> None: ...

global___ConfigureResponse = ConfigureResponse

class SessionID(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    session_id: builtins.int
    def __init__(
        self,
        *,
        session_id: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["session_id", b"session_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["session_id", b"session_id"]) -> None: ...

global___SessionID = SessionID

class ConvertObservationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    OBSERVATION_FIELD_NUMBER: builtins.int
    session_id: builtins.int
    @property
    def observation(self) -> converter_pb2.Observation: ...
    def __init__(
        self,
        *,
        session_id: builtins.int | None = ...,
        observation: converter_pb2.Observation | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["observation", b"observation", "session_id", b"session_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["observation", b"observation", "session_id", b"session_id"]) -> None: ...

global___ConvertObservationRequest = ConvertObservationRequest

class ConvertActionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    ACTION_FIELD_NUMBER: builtins.int
    session_id: builtins.int
    @property
    def action(self) -> converter_pb2.Action: ...
    def __init__(
        self,
        *,
        session_id: builtins.int | None = ...,
        action: converter_pb2.Action | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["action", b"action", "session_id", b"session_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["action", b"action", "session_id", b"session_id"]) -> None: ...

global___ConvertActionRequest = ConvertActionRequest

class ObservationSpec(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class SpecsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.bytes
        def __init__(
            self,
            *,
            key: builtins.str | None = ...,
            value: builtins.bytes | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    SPECS_FIELD_NUMBER: builtins.int
    @property
    def specs(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.bytes]:
        """A map of strings (feature names) to serialized `dm_env_rpc.v1.TensorSpec` bytes"""
    def __init__(
        self,
        *,
        specs: collections.abc.Mapping[builtins.str, builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["specs", b"specs"]) -> None: ...

global___ObservationSpec = ObservationSpec

class ActionSpec(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class SpecsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.bytes
        def __init__(
            self,
            *,
            key: builtins.str | None = ...,
            value: builtins.bytes | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    SPECS_FIELD_NUMBER: builtins.int
    @property
    def specs(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.bytes]:
        """A map of strings (action names) to serialized `dm_env_rpc.v1.TensorSpec` bytes"""
    def __init__(
        self,
        *,
        specs: collections.abc.Mapping[builtins.str, builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["specs", b"specs"]) -> None: ...

global___ActionSpec = ActionSpec

class ConvertedObservation(google.protobuf.message.Message):
    """Represents the dynamically sized output data per frame"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class TensorsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.bytes
        def __init__(
            self,
            *,
            key: builtins.str | None = ...,
            value: builtins.bytes | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    TENSORS_FIELD_NUMBER: builtins.int
    @property
    def tensors(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.bytes]:
        """A map of strings (feature names) to serialized `dm_env_rpc.v1.Tensor` bytes"""
    def __init__(
        self,
        *,
        tensors: collections.abc.Mapping[builtins.str, builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["tensors", b"tensors"]) -> None: ...

global___ConvertedObservation = ConvertedObservation

class ActionRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class TensorsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.bytes
        def __init__(
            self,
            *,
            key: builtins.str | None = ...,
            value: builtins.bytes | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    TENSORS_FIELD_NUMBER: builtins.int
    @property
    def tensors(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.bytes]:
        """A map of strings (action names) to serialized `dm_env_rpc.v1.Tensor` bytes"""
    def __init__(
        self,
        *,
        tensors: collections.abc.Mapping[builtins.str, builtins.bytes] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["tensors", b"tensors"]) -> None: ...

global___ActionRequest = ActionRequest
