# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pysc2.env.converter.proto import converter_pb2 as pysc2_dot_env_dot_converter_dot_proto_dot_converter__pb2
import pysc2_converter_external.proto.service_pb2 as service__pb2


class ExternalConverterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConfigureConverter = channel.unary_unary(
                '/ExternalConverterService/ConfigureConverter',
                request_serializer=service__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=service__pb2.ConfigureResponse.FromString,
                )
        self.GetObservationSpec = channel.unary_unary(
                '/ExternalConverterService/GetObservationSpec',
                request_serializer=service__pb2.SessionID.SerializeToString,
                response_deserializer=service__pb2.ObservationSpec.FromString,
                )
        self.GetActionSpec = channel.unary_unary(
                '/ExternalConverterService/GetActionSpec',
                request_serializer=service__pb2.SessionID.SerializeToString,
                response_deserializer=service__pb2.ActionSpec.FromString,
                )
        self.ConvertObservation = channel.unary_unary(
                '/ExternalConverterService/ConvertObservation',
                request_serializer=service__pb2.ConvertObservationRequest.SerializeToString,
                response_deserializer=service__pb2.ConvertedObservation.FromString,
                )
        self.ConvertAction = channel.unary_unary(
                '/ExternalConverterService/ConvertAction',
                request_serializer=service__pb2.ConvertActionRequest.SerializeToString,
                response_deserializer=pysc2_dot_env_dot_converter_dot_proto_dot_converter__pb2.Action.FromString,
                )


class ExternalConverterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConfigureConverter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObservationSpec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActionSpec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertObservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExternalConverterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConfigureConverter': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureConverter,
                    request_deserializer=service__pb2.ConfigureRequest.FromString,
                    response_serializer=service__pb2.ConfigureResponse.SerializeToString,
            ),
            'GetObservationSpec': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObservationSpec,
                    request_deserializer=service__pb2.SessionID.FromString,
                    response_serializer=service__pb2.ObservationSpec.SerializeToString,
            ),
            'GetActionSpec': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActionSpec,
                    request_deserializer=service__pb2.SessionID.FromString,
                    response_serializer=service__pb2.ActionSpec.SerializeToString,
            ),
            'ConvertObservation': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertObservation,
                    request_deserializer=service__pb2.ConvertObservationRequest.FromString,
                    response_serializer=service__pb2.ConvertedObservation.SerializeToString,
            ),
            'ConvertAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertAction,
                    request_deserializer=service__pb2.ConvertActionRequest.FromString,
                    response_serializer=pysc2_dot_env_dot_converter_dot_proto_dot_converter__pb2.Action.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ExternalConverterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExternalConverterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConfigureConverter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ExternalConverterService/ConfigureConverter',
            service__pb2.ConfigureRequest.SerializeToString,
            service__pb2.ConfigureResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetObservationSpec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ExternalConverterService/GetObservationSpec',
            service__pb2.SessionID.SerializeToString,
            service__pb2.ObservationSpec.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetActionSpec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ExternalConverterService/GetActionSpec',
            service__pb2.SessionID.SerializeToString,
            service__pb2.ActionSpec.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConvertObservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ExternalConverterService/ConvertObservation',
            service__pb2.ConvertObservationRequest.SerializeToString,
            service__pb2.ConvertedObservation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ConvertAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ExternalConverterService/ConvertAction',
            service__pb2.ConvertActionRequest.SerializeToString,
            pysc2_dot_env_dot_converter_dot_proto_dot_converter__pb2.Action.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
