# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pysc2_converter_external.proto.converter_pb2 as converter__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x1a\x0f\x63onverter.proto\"p\n\x10\x43onfigureRequest\x12*\n\x08settings\x18\x01 \x02(\x0b\x32\x18.pysc2.ConverterSettings\x12\x30\n\x10\x65nvironment_info\x18\x02 \x02(\x0b\x32\x16.pysc2.EnvironmentInfo\"8\n\x11\x43onfigureResponse\x12\x0f\n\x07success\x18\x01 \x02(\x08\x12\x12\n\nsession_id\x18\x02 \x02(\x04\"\x1f\n\tSessionID\x12\x12\n\nsession_id\x18\x01 \x02(\x04\"X\n\x19\x43onvertObservationRequest\x12\x12\n\nsession_id\x18\x01 \x02(\x04\x12\'\n\x0bobservation\x18\x02 \x02(\x0b\x32\x12.pysc2.Observation\"I\n\x14\x43onvertActionRequest\x12\x12\n\nsession_id\x18\x01 \x02(\x04\x12\x1d\n\x06\x61\x63tion\x18\x02 \x02(\x0b\x32\r.pysc2.Action\"k\n\x0fObservationSpec\x12*\n\x05specs\x18\x01 \x03(\x0b\x32\x1b.ObservationSpec.SpecsEntry\x1a,\n\nSpecsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"a\n\nActionSpec\x12%\n\x05specs\x18\x01 \x03(\x0b\x32\x16.ActionSpec.SpecsEntry\x1a,\n\nSpecsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"{\n\x14\x43onvertedObservation\x12\x33\n\x07tensors\x18\x01 \x03(\x0b\x32\".ConvertedObservation.TensorsEntry\x1a.\n\x0cTensorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"m\n\rActionRequest\x12,\n\x07tensors\x18\x01 \x03(\x0b\x32\x1b.ActionRequest.TensorsEntry\x1a.\n\x0cTensorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x32\xbf\x02\n\x18\x45xternalConverterService\x12=\n\x12\x43onfigureConverter\x12\x11.ConfigureRequest\x1a\x12.ConfigureResponse\"\x00\x12\x34\n\x12GetObservationSpec\x12\n.SessionID\x1a\x10.ObservationSpec\"\x00\x12*\n\rGetActionSpec\x12\n.SessionID\x1a\x0b.ActionSpec\"\x00\x12I\n\x12\x43onvertObservation\x12\x1a.ConvertObservationRequest\x1a\x15.ConvertedObservation\"\x00\x12\x37\n\rConvertAction\x12\x15.ConvertActionRequest\x1a\r.pysc2.Action\"\x00')



_CONFIGUREREQUEST = DESCRIPTOR.message_types_by_name['ConfigureRequest']
_CONFIGURERESPONSE = DESCRIPTOR.message_types_by_name['ConfigureResponse']
_SESSIONID = DESCRIPTOR.message_types_by_name['SessionID']
_CONVERTOBSERVATIONREQUEST = DESCRIPTOR.message_types_by_name['ConvertObservationRequest']
_CONVERTACTIONREQUEST = DESCRIPTOR.message_types_by_name['ConvertActionRequest']
_OBSERVATIONSPEC = DESCRIPTOR.message_types_by_name['ObservationSpec']
_OBSERVATIONSPEC_SPECSENTRY = _OBSERVATIONSPEC.nested_types_by_name['SpecsEntry']
_ACTIONSPEC = DESCRIPTOR.message_types_by_name['ActionSpec']
_ACTIONSPEC_SPECSENTRY = _ACTIONSPEC.nested_types_by_name['SpecsEntry']
_CONVERTEDOBSERVATION = DESCRIPTOR.message_types_by_name['ConvertedObservation']
_CONVERTEDOBSERVATION_TENSORSENTRY = _CONVERTEDOBSERVATION.nested_types_by_name['TensorsEntry']
_ACTIONREQUEST = DESCRIPTOR.message_types_by_name['ActionRequest']
_ACTIONREQUEST_TENSORSENTRY = _ACTIONREQUEST.nested_types_by_name['TensorsEntry']
ConfigureRequest = _reflection.GeneratedProtocolMessageType('ConfigureRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGUREREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:ConfigureRequest)
  })
_sym_db.RegisterMessage(ConfigureRequest)

ConfigureResponse = _reflection.GeneratedProtocolMessageType('ConfigureResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGURERESPONSE,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:ConfigureResponse)
  })
_sym_db.RegisterMessage(ConfigureResponse)

SessionID = _reflection.GeneratedProtocolMessageType('SessionID', (_message.Message,), {
  'DESCRIPTOR' : _SESSIONID,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:SessionID)
  })
_sym_db.RegisterMessage(SessionID)

ConvertObservationRequest = _reflection.GeneratedProtocolMessageType('ConvertObservationRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONVERTOBSERVATIONREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:ConvertObservationRequest)
  })
_sym_db.RegisterMessage(ConvertObservationRequest)

ConvertActionRequest = _reflection.GeneratedProtocolMessageType('ConvertActionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CONVERTACTIONREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:ConvertActionRequest)
  })
_sym_db.RegisterMessage(ConvertActionRequest)

ObservationSpec = _reflection.GeneratedProtocolMessageType('ObservationSpec', (_message.Message,), {

  'SpecsEntry' : _reflection.GeneratedProtocolMessageType('SpecsEntry', (_message.Message,), {
    'DESCRIPTOR' : _OBSERVATIONSPEC_SPECSENTRY,
    '__module__' : 'service_pb2'
    # @@protoc_insertion_point(class_scope:ObservationSpec.SpecsEntry)
    })
  ,
  'DESCRIPTOR' : _OBSERVATIONSPEC,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:ObservationSpec)
  })
_sym_db.RegisterMessage(ObservationSpec)
_sym_db.RegisterMessage(ObservationSpec.SpecsEntry)

ActionSpec = _reflection.GeneratedProtocolMessageType('ActionSpec', (_message.Message,), {

  'SpecsEntry' : _reflection.GeneratedProtocolMessageType('SpecsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ACTIONSPEC_SPECSENTRY,
    '__module__' : 'service_pb2'
    # @@protoc_insertion_point(class_scope:ActionSpec.SpecsEntry)
    })
  ,
  'DESCRIPTOR' : _ACTIONSPEC,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:ActionSpec)
  })
_sym_db.RegisterMessage(ActionSpec)
_sym_db.RegisterMessage(ActionSpec.SpecsEntry)

ConvertedObservation = _reflection.GeneratedProtocolMessageType('ConvertedObservation', (_message.Message,), {

  'TensorsEntry' : _reflection.GeneratedProtocolMessageType('TensorsEntry', (_message.Message,), {
    'DESCRIPTOR' : _CONVERTEDOBSERVATION_TENSORSENTRY,
    '__module__' : 'service_pb2'
    # @@protoc_insertion_point(class_scope:ConvertedObservation.TensorsEntry)
    })
  ,
  'DESCRIPTOR' : _CONVERTEDOBSERVATION,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:ConvertedObservation)
  })
_sym_db.RegisterMessage(ConvertedObservation)
_sym_db.RegisterMessage(ConvertedObservation.TensorsEntry)

ActionRequest = _reflection.GeneratedProtocolMessageType('ActionRequest', (_message.Message,), {

  'TensorsEntry' : _reflection.GeneratedProtocolMessageType('TensorsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ACTIONREQUEST_TENSORSENTRY,
    '__module__' : 'service_pb2'
    # @@protoc_insertion_point(class_scope:ActionRequest.TensorsEntry)
    })
  ,
  'DESCRIPTOR' : _ACTIONREQUEST,
  '__module__' : 'service_pb2'
  # @@protoc_insertion_point(class_scope:ActionRequest)
  })
_sym_db.RegisterMessage(ActionRequest)
_sym_db.RegisterMessage(ActionRequest.TensorsEntry)

_EXTERNALCONVERTERSERVICE = DESCRIPTOR.services_by_name['ExternalConverterService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBSERVATIONSPEC_SPECSENTRY._options = None
  _OBSERVATIONSPEC_SPECSENTRY._serialized_options = b'8\001'
  _ACTIONSPEC_SPECSENTRY._options = None
  _ACTIONSPEC_SPECSENTRY._serialized_options = b'8\001'
  _CONVERTEDOBSERVATION_TENSORSENTRY._options = None
  _CONVERTEDOBSERVATION_TENSORSENTRY._serialized_options = b'8\001'
  _ACTIONREQUEST_TENSORSENTRY._options = None
  _ACTIONREQUEST_TENSORSENTRY._serialized_options = b'8\001'
  _CONFIGUREREQUEST._serialized_start=34
  _CONFIGUREREQUEST._serialized_end=146
  _CONFIGURERESPONSE._serialized_start=148
  _CONFIGURERESPONSE._serialized_end=204
  _SESSIONID._serialized_start=206
  _SESSIONID._serialized_end=237
  _CONVERTOBSERVATIONREQUEST._serialized_start=239
  _CONVERTOBSERVATIONREQUEST._serialized_end=327
  _CONVERTACTIONREQUEST._serialized_start=329
  _CONVERTACTIONREQUEST._serialized_end=402
  _OBSERVATIONSPEC._serialized_start=404
  _OBSERVATIONSPEC._serialized_end=511
  _OBSERVATIONSPEC_SPECSENTRY._serialized_start=467
  _OBSERVATIONSPEC_SPECSENTRY._serialized_end=511
  _ACTIONSPEC._serialized_start=513
  _ACTIONSPEC._serialized_end=610
  _ACTIONSPEC_SPECSENTRY._serialized_start=467
  _ACTIONSPEC_SPECSENTRY._serialized_end=511
  _CONVERTEDOBSERVATION._serialized_start=612
  _CONVERTEDOBSERVATION._serialized_end=735
  _CONVERTEDOBSERVATION_TENSORSENTRY._serialized_start=689
  _CONVERTEDOBSERVATION_TENSORSENTRY._serialized_end=735
  _ACTIONREQUEST._serialized_start=737
  _ACTIONREQUEST._serialized_end=846
  _ACTIONREQUEST_TENSORSENTRY._serialized_start=689
  _ACTIONREQUEST_TENSORSENTRY._serialized_end=735
  _EXTERNALCONVERTERSERVICE._serialized_start=849
  _EXTERNALCONVERTERSERVICE._serialized_end=1168
# @@protoc_insertion_point(module_scope)
